import type { GameState, OwnedCard, SkillId } from "./types";
import { DECK_SIZE, DUNGEON_STAMINA_MAX } from "./types";
import { initRng, rollNewRngSeed } from "./rng";
import { playerMaxHp } from "./systems/playerCombat";
import { emptyGardenPlots } from "./systems/spiritGarden";
import { emptyWeeklyBounty, currentWeekKey } from "./systems/weeklyBounty";
import { emptyCelestialStash } from "./systems/celestialStash";
import { createEmptyEstateCommissionState } from "./systems/estateCommission";

export const SAVE_VERSION = 99;

const emptySkills = (): GameState["skills"] => ({
  combat: { level: 1, xp: 0 },
  gathering: { level: 1, xp: 0 },
  arcana: { level: 1, xp: 0 },
});

/** 新档 / 轮回等场景复用，避免与 `createInitialState` 漂移 */
export const emptyDungeon = (): GameState["dungeon"] => ({
  active: false,
  wave: 1,
  monsterHp: 0,
  monsterMax: 0,
  playerHp: 0,
  playerMax: 0,
  deathCooldownUntil: 0,
  totalWavesCleared: 0,
  monsterAttackAccum: 0,
  playerAttackAccum: 0,
  playerAttackTargetMobId: 0,
  packSize: 1,
  packKilled: 0,
  sessionKills: 0,
  sessionEssence: 0,
  essenceRemainder: 0,
  playerX: 0.5,
  playerY: 0.5,
  mobs: [],
  nextMobId: 1,
  walkable: [],
  mapW: 0,
  mapH: 0,
  maxWaveRecord: 0,
  entryWave: 1,
  attackAnimPhase: 0,
  inMelee: false,
  attackVisualMode: "none",
  interWaveCooldownUntil: 0,
  essenceThisWave: 0,
  pendingToast: null,
  pendingKillToast: null,
  waveCheckpoint: {},
  waveEntrySpawnX: 0.5,
  waveEntrySpawnY: 0.5,
  bossDodgeVisual: false,
  stamina: DUNGEON_STAMINA_MAX,
  dodgeIframesUntil: 0,
  dodgeQueued: false,
  playerMoveLockUntil: 0,
  playerLastMoveNx: 0,
  playerLastMoveNy: 0,
  rewardModeRepeat: false,
  autoEnterConsumed: false,
  sessionEnterAtMs: 0,
  duelComboStacks: 0,
  duelWeakUntilMs: 0,
  duelWeakNextAtMs: 0,
  duelFervor: 0,
  duelElemSurgeCounter: 0,
  bossPrepKills: 0,
  bossPrepChallengeReady: false,
});

export function createInitialState(): GameState {
  const now = Date.now();
  const day = `${new Date(now).getFullYear()}-${String(new Date(now).getMonth() + 1).padStart(2, "0")}-${String(new Date(now).getDate()).padStart(2, "0")}`;
  const seed = rollNewRngSeed();
  const st: GameState = {
    version: SAVE_VERSION,
    spiritStones: "0",
    peakSpiritStonesThisLife: "0",
    summonEssence: 72,
    zhuLingEssence: 36,
    daoEssence: 0,
    zaoHuaYu: 0,
    realmLevel: 1,
    totalPulls: 0,
    pityUr: 0,
    pitySsrSoft: 0,
    gearPityPulls: 0,
    owned: {},
    deck: Array.from({ length: DECK_SIZE }, () => null),
    codexUnlocked: new Set(),
    reincarnations: 0,
    meta: {
      idleMult: 0,
      gachaLuck: 0,
      deckSlots: 0,
      ticketRegen: 0,
      stoneMult: 0,
    },
    achievementsDone: new Set(),
    lastTick: now,
    playtimeSec: 0,
    lifePlaytimeSec: 0,
    rngSeed: "",
    rngStateJson: "",
    inGameHour: 3,
    inGameDay: 1,
    lifeStartInGameDay: 1,
    gameHourTickAccum: 0,
    fenTianCooldownUntil: 0,
    biGuanCooldownUntil: 0,
    qoL: {
      tenPull: false,
      bulkLevel: false,
      autoRealm: false,
      autoGacha: false,
      autoTuna: false,
    },
    lastAutoGachaMs: 0,
    lastAutoGearForgeMs: 0,
    lastAutoBossChallengeMs: 0,
    autoSalvageAccumSec: 0,
    trueEndingSeen: false,
    tutorialStep: 1,
    featureGuideDismissed: [],
    suppressFeatureGuides: false,
    uiPrefs: {
      reduceMotion: false,
      compactNumbers: true,
      soundMuted: false,
      masterVolume: 0.85,
      autoClaimSpiritReservoir: false,
      autoHarvestSpiritGarden: false,
      autoClaimDailyLogin: false,
      autoClaimWeeklyBounty: false,
      autoSettleEstateCommission: false,
      autoRedeemCelestialStash: false,
      autoFeedPets: false,
      autoUpgradeSpiritArray: false,
      autoPullBattleSkill: false,
      autoBuyDaoMeridian: false,
      autoUpgradeVein: false,
      autoBuyMeta: false,
      confirmReincarnation: true,
      dynamicDocumentTitle: true,
      showIncomeGuidePanel: true,
    },
    vein: { huiLing: 0, guYuan: 0, lingXi: 0, gongMing: 0 },
    pullsThisLife: 0,
    lingSha: 0,
    xuanTie: 0,
    salvageAuto: { n: false, r: false, gearN: false, gearR: false },
    battleSkills: {},
    wishResonance: 0,
    firstOpenTodayMs: now,
    dailyStreak: 1,
    lastLoginCalendarDate: day,
    dailyLoginTickDay: null,
    dailyLoginClaimedDate: null,
    loginCalendarWeekKey: currentWeekKey(now),
    loginCalendarClaimedDates: [],
    loginCalendarWeeklyBonusClaimed: false,
    lastTunaMs: 0,
    skills: emptySkills(),
    activeSkillId: "combat" as SkillId | null,
    dungeon: emptyDungeon(),
    gearInventory: {},
    equippedGear: {
      weapon: null,
      body: null,
      ring: null,
      slot4: null,
      slot5: null,
      slot6: null,
      slot7: null,
      slot8: null,
      slot9: null,
      slot10: null,
      slot11: null,
      slot12: null,
    },
    gearSlotEnhance: {
      weapon: 0,
      body: 0,
      ring: 0,
      slot4: 0,
      slot5: 0,
      slot6: 0,
      slot7: 0,
      slot8: 0,
      slot9: 0,
      slot10: 0,
      slot11: 0,
      slot12: 0,
    },
    nextGearInstanceId: 1,
    gearInventorySort: "rarity",
    pets: {},
    petPullsTotal: 0,
    spiritGarden: { plots: emptyGardenPlots(), totalHarvests: 0 },
    weeklyBounty: emptyWeeklyBounty(currentWeekKey(now)),
    celestialStash: emptyCelestialStash(currentWeekKey(now)),
    spiritReservoirStored: "0",
    dailyFortune: { calendarDay: "", fortuneId: "fd_he" },
    offlineAdventure: {
      pending: null,
      activeBoostUntilMs: 0,
      activeBoostMult: 1,
      resonanceType: null,
      resonanceStacks: 0,
      autoPolicyEnabled: false,
      autoPolicy: "steady",
      autoRerollEnabled: false,
      autoRerollBudgetStones: "0",
      lastAutoSettleReceipt: null,
    },
    estateCommission: createEmptyEstateCommissionState(),
    spiritArrayLevel: 0,
    daoMeridian: 0,
    pullChronicle: [],
    gearPullChronicle: [],
    lifetimeStats: {
      dungeonEssenceIntGained: 0,
      celestialStashBuys: 0,
      spiritReservoirClaims: 0,
      dailyFortuneRolls: 0,
      gearForgesTotal: 0,
      maxGearRarityRankForged: 0,
      weeklyBountyFullWeeks: 0,
      lastWeeklyBountyFullWeekKey: "",
      offlineAdventureBoostPicks: 0,
      loginCalendarFullWeeks: 0,
      lastLoginCalendarFullWeekKey: "",
      resonanceEssencePayouts: 0,
      tunaCompletions: 0,
      fenTianBursts: 0,
      estateCommissionCompletions: 0,
      battleSkillPulls: 0,
      gearSalvages: 0,
      cardSalvages: 0,
      veinUpgrades: 0,
      offlineAdventureCompletions: 0,
      metaUpgrades: 0,
      petFeeds: 0,
      gardenPlants: 0,
      skillLevelUps: 0,
      realmBreakthroughs: 0,
      gearEnhances: 0,
      urGearRefines: 0,
      cardLevelUps: 0,
      cardStarUps: 0,
      spiritTideHours: 0,
      spiritArrayUpgrades: 0,
      biGuanCompletions: 0,
      cardTenPullSessions: 0,
      gearTenPullSessions: 0,
      dailyLoginDayClaims: 0,
      offlineStoneSettlements: 0,
      maxInGameDayReached: 1,
      cardSinglePullActions: 0,
      gearSinglePullActions: 0,
      dungeonBossKills: 0,
      dungeonRollDodges: 0,
      daoEssenceSpentLifetime: 0,
      summonEssenceSpentLifetime: 0,
      zhuLingEssenceSpentLifetime: 0,
      lingShaSpentLifetime: 0,
      xuanTieSpentLifetime: 0,
      zaoHuaYuSpentLifetime: 0,
    },
    combatHpCurrent: 100,
    dungeonSanctuaryMode: false,
    dungeonPortalTargetWave: 0,
    dungeonSanctuaryAutoEnter: true,
    dungeonDeferBoss: true,
    autoGearForge: false,
    autoBossChallenge: false,
  };
  initRng(st, seed);
  st.combatHpCurrent = playerMaxHp(st);
  return st;
}

export function ensureOwned(state: GameState, defId: string): OwnedCard {
  let o = state.owned[defId];
  if (!o) {
    o = { defId, stars: 0, level: 1 };
    state.owned[defId] = o;
  }
  return o;
}

export function countUniqueOwned(state: GameState): number {
  return Object.keys(state.owned).length;
}
